import Project.ConnectionProvider;
import java.awt.Component;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nikita
 */
public class studentCompany extends javax.swing.JFrame {
public String rollNo,company_id1;

//private void updateRowHeights()
//{
//try 
//{
//    for (int row = 0; row < jTable1.getRowCount(); row++)
//    {
//        int rowHeight = jTable1.getRowHeight();
//
//        for (int column = 0; column < jTable1.getColumnCount(); column++)
//        {
//            Component comp = jTable1.prepareRenderer(jTable1.getCellRenderer(row, column), row, column);
//            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
//        }
//
//        jTable1.setRowHeight(row, rowHeight);
//    }
//}
//catch(ClassCastException e) {
//    JOptionPane.showMessageDialog(null,e);
//}}
    /**
     * Creates new form studentCompany
     */
    public studentCompany() {
        initComponents();
    }

    public studentCompany(String rollNo1) {
       initComponents();
       rollNo=rollNo1;
       try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from company");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            Statement st01=con.createStatement();
            ResultSet rs01=st01.executeQuery("select count(company_id) from company_student where student_id='"+rollNo+"'");
            rs01.next();
            String count=rs01.getString(1);
            if(count.equals("0")){
                jButton3.setEnabled(false);
            }            
//jTable1.getColumnModel().getColumn(columnIndex).setCellRenderer(renderer);
            //updateRowHeights();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
 }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setText("Choose a Company!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 1366, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Enter The Company Id :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 199, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Take the Quiz!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backhome.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 11, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 179, 629, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all student result.png"))); // NOI18N
        jButton3.setText("Dashboard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/companybg.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginStudent().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String company_id=jTextField1.getText();
         int c=0,shift=0;
         String tech_marks="none";
         String log_marks="none";
         String eng_marks="none";
         String s_marks="none";  
         String tot="none";
         try{
            Connection con=ConnectionProvider.getCon();
            Statement st0=con.createStatement();
            ResultSet rs=st0.executeQuery("select id from company where id='"+company_id+"'");
            int comp_id=Integer.parseInt(company_id);
            if(rs.next()){
                Statement st1=con.createStatement();
                ResultSet rs2=st1.executeQuery("select technical_marks,logical_marks,engProf_marks,situation_marks from company_student where student_id='"+rollNo+"' and company_id='"+comp_id+"'");
                //ResultSet rs2=st1.executeQuery("select * from company_student where student_id='19101A0090' and company_id='"+comp_id+"'");
                if(rs2.next()){
                String t_marks=rs2.getString(1);
                String l_marks=rs2.getString(2);
                String e_marks=rs2.getString(3);
                String sit_marks=rs2.getString(4);
                if(!t_marks.equals("none") && !l_marks.equals("none") && !e_marks.equals("none") && !sit_marks.equals("none")){
                    //System.out.println("coming");
                    JOptionPane.showMessageDialog(null,"You have already attempted the interview for this company.\nYou Cannot attempt it again!");
                    shift=1;
                    }else{
                        setVisible(false);
                        new StudentQuizSection(company_id,rollNo).setVisible(true);
                    }
                }else if(shift==0){
                    //System.out.println("no record");
                    Statement st3=con.createStatement();
                    ResultSet rs3=st3.executeQuery("select count(id) from company_student");
                    rs3.first();
                    int id=rs3.getInt(1);
                    id=id+1;
                    PreparedStatement ps=con.prepareStatement("insert into company_student values (?,?,?,?,?,?,?,?)");
                    ps.setInt(1,id);
                    ps.setString(2, rollNo);
                    ps.setString(3,company_id);
                    ps.setString(4, tech_marks);
                    ps.setString(5,log_marks);
                    ps.setString(6,eng_marks);
                    ps.setString(7,s_marks);
                    ps.setString(8, tot);
                    ps.executeUpdate();
                    setVisible(false);
                    new StudentQuizSection(company_id,rollNo).setVisible(true);
                }
//                }else if(shift==0){
//                    Statement st3=con.createStatement();
//                    ResultSet rs3=st3.executeQuery("select count(id) from company_student");
//                    rs3.first();
//                    int id=rs3.getInt(1);
//                    id=id+1;
//                    PreparedStatement ps=con.prepareStatement("insert into company_student values (?,?,?,?,?,?,?)");
//                    ps.setInt(1,id);
//                    ps.setString(2, rollNo);
//                    ps.setString(3,company_id);
//                    ps.setString(4, tech_marks);
//                    ps.setString(5,log_marks);
//                    ps.setString(6,eng_marks);
//                    ps.setString(7,s_marks);
//                    ps.executeUpdate();
//                    setVisible(false);
//                    new StudentQuizSection(company_id,rollNo).setVisible(true);
 //
 //           }
                
//                  if(!rs2.first()){
//                    Statement st2=(Statement) con.createStatement();
//                    ResultSet rs3=st2.executeQuery("select count(id) from company_student");
//                    rs3.first();
//                    int id=rs2.getInt(1);
//                    System.out.println(id);
//                    PreparedStatement ps=con.prepareStatement("insert into company_student values (?,?,?,?,?,?,?)");
//                    ps.setInt(1,1);
//                    ps.setString(2, rollNo);
//                    ps.setString(3,company_id);
//                    ps.setString(4, tech_marks);
//                    ps.setString(5,log_marks);
//                    ps.setString(6,eng_marks);
//                    ps.setString(7,s_marks);
//                    ps.executeUpdate();
//         
//                }
                
//                String t_marks=rs2.getString(4);
//                String l_marks=rs2.getString(5);
//                String e_marks=rs2.getString(6);
//                String s_marks=rs2.getString(7);
//                if(t_marks.equals("-1") || l_marks.equals("-1") || e_marks.equals("-1") || s_marks.equals("-1")){
//                    setVisible(false);
//                    new StudentQuizSection(company_id1,rollNo).setVisible(true);
//                }else{
//                    JOptionPane.showMessageDialog(null,"You have already attempted the interview for this company.\nYou Cannot attempt it again!");
//                }
            }else{
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
               JOptionPane.showMessageDialog(jf,"Please Enter the valid company Id from the table shown below!");
            }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
//         if(c==1){
//            try{
//                Connection conn=ConnectionProvider.getCon();
//                Statement st3=conn.createStatement();
//                ResultSet rs3=st3.executeQuery("select count(id) from company_student");
//                 rs3.first();
//                 int id=rs3.getInt(1);
//                 id=id+1;
//                 //System.out.println(id);
//               PreparedStatement ps=conn.prepareStatement("insert into company_student values (?,?,?,?,?,?,?)");
//                  ps.setInt(1,id);
//                  ps.setString(2, rollNo);
//                  ps.setString(3,company_id);
//                  ps.setString(4, tech_marks);
//                  ps.setString(5,log_marks);
//                  ps.setString(6,eng_marks);
//                  ps.setString(7,s_marks);
//                  ps.executeUpdate();
//                  JOptionPane.showMessageDialog(null,"User registered Successfully! Please Login Again! Your username is your Roll no!");
//                  shift=30;
////                  new StudentQuizSection(company_id,rollNo).setVisible(true);
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(null,e);
//            }
//         }
//        System.out.println(shift);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Dashboard(rollNo).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
